import React from 'react';
import type { ChapterNote, Dpp } from '@/types';
import type { BankQuestion } from '@/ai/questionBank';

/* Pure A4 content blocks — always rendered inside <PrintSheet>'s .sheet. */

interface Ctx {
  courseTitle: string;
  courseShort: string;
  chapterTitle: string;
}

function SheetHead({ right }: { right: string }) {
  return (
    <div className="sheet-head">
      <span className="sheet-brand">MAKAUT NEXUS · Student Library</span>
      <span>{right}</span>
    </div>
  );
}

function SheetFoot({ text }: { text: string }) {
  return <div className="sheet-foot">{text}</div>;
}

/* ── 1. Chapter notes on paper ─────────────────────────────────── */

export function NotePaper({ ctx, note }: { ctx: Ctx; note: ChapterNote }) {
  return (
    <>
      <SheetHead right={`${ctx.courseTitle} · ${ctx.chapterTitle}`} />
      <h1>{note.title}</h1>
      <div className="sheet-sub">Chapter notes · {note.readMinutes} min read · free educational material — print & study offline</div>
      {note.sections.map((sec) => (
        <div key={sec.heading} className="sheet-block">
          <h2>{sec.heading}</h2>
          <ul>
            {sec.bullets.map((b, i) => (
              <li key={i}>{b}</li>
            ))}
          </ul>
        </div>
      ))}
      <SheetFoot text="Printed from the free MAKAUT NEXUS student library · Cross-check provisional items against official university sources." />
    </>
  );
}

/* ── 2. Slide deck (presentation) on paper ─────────────────────── */

export function SlidesPaper({ ctx, note }: { ctx: Ctx; note: ChapterNote }) {
  const total = note.sections.length + 2;
  let n = 1;
  return (
    <>
      <div className="slide slide--cover">
        <div className="slide-kicker">MAKAUT NEXUS · printable slide deck</div>
        <h1>{ctx.chapterTitle}</h1>
        <p className="slide-sub">{note.title}</p>
        <p className="slide-meta">{ctx.courseTitle} ({ctx.courseShort})</p>
      </div>

      {note.sections.map((sec) => {
        const num = ++n;
        return (
          <div className="slide page-break" key={sec.heading}>
            <div className="slide-no">
              {num} / {total}
            </div>
            <h2>{sec.heading}</h2>
            <ul>
              {sec.bullets.map((b, i) => (
                <li key={i}>{b}</li>
              ))}
            </ul>
          </div>
        );
      })}

      <div className="slide slide--end page-break">
        <div className="slide-no">
          {++n} / {total}
        </div>
        <h1>End of deck</h1>
        <p className="slide-sub">Open this chapter in the NEXUS library for free books, video lectures and the practice DPP.</p>
        <p className="slide-meta">
          {ctx.courseTitle} · {ctx.chapterTitle}
        </p>
      </div>
      <SheetFoot text="Slide deck exported from MAKAUT NEXUS · one A4 page = one slide." />
    </>
  );
}

/* ── 3. DPP paper (questions) + separate answer key ────────────── */

export function DppPaper({ ctx, dpp }: { ctx: Ctx; dpp: Dpp }) {
  return (
    <>
      <SheetHead right={`${ctx.courseTitle} · ${ctx.chapterTitle}`} />
      <div className="paper-title-row">
        <h1>{dpp.title}</h1>
        <div className="paper-meta">Marks: {dpp.questions.length}</div>
      </div>
      <div className="paper-fields">
        <span>Name: ______________________</span>
        <span>Roll No.: ______________</span>
        <span>Date: ____________</span>
        <span>Time: __________</span>
        <span>Signature: ____________</span>
      </div>
      <div className="sheet-note">
        Answer all {dpp.questions.length} questions. Show your working in the space provided — solutions are on the last page.
      </div>

      <ol className="paper-qs">
        {dpp.questions.map((q) => (
          <li key={q.id} className="paper-q page-break-inside">
            <div className="q-prompt">{q.prompt}</div>
            <div className="lines">
              <span />
              <span />
              <span />
            </div>
          </li>
        ))}
      </ol>

      <div className="page-break" />
      <SheetHead right={`${ctx.courseTitle} · answer key`} />
      <h1>Answer key & solutions</h1>
      <div className="sheet-sub">{dpp.title} — check your work after attempting the paper</div>
      {dpp.questions.map((q, i) => (
        <div key={q.id} className="key-item page-break-inside">
          <div className="key-ans">
            {i + 1}. {q.answer}
          </div>
          <ol>
            {q.solution.map((s, si) => (
              <li key={si}>{s}</li>
            ))}
          </ol>
        </div>
      ))}
      <SheetFoot text="DPP generated by MAKAUT NEXUS · free forever. Verify values against your faculty's conventions." />
    </>
  );
}

/* ── 4. Printable MCQ test paper + answer key ──────────────────── */

export function McqTestPaper({ courseTitle, courseShort, questions }: { courseTitle: string; courseShort: string; questions: BankQuestion[] }) {
  const mins = questions.length;
  return (
    <>
      <SheetHead right={`${courseTitle} (${courseShort})`} />
      <div className="paper-title-row">
        <h1>{courseTitle} — MCQ Test Paper</h1>
        <div className="paper-meta">
          Q: {questions.length} · Time: {mins} min
        </div>
      </div>
      <div className="paper-fields">
        <span>Name: ______________________</span>
        <span>Roll No.: ______________</span>
        <span>Date: ____________</span>
        <span>Marks: ______ / {questions.length}</span>
        <span>Signature: ____________</span>
      </div>
      <div className="sheet-note">
        Tick (✓) one option per question. Each question carries 1 mark; no negative marking. Suggested time: {mins} minutes.
      </div>

      <ol className="paper-qs">
        {questions.map((q) => (
          <li key={q.id} className="paper-q page-break-inside">
            <div className="q-prompt">{q.text}</div>
            <div className="opts">
              {q.options.map((o, oi) => (
                <span key={oi}>
                  <b>{'ABCD'[oi]}.</b> {o}
                </span>
              ))}
            </div>
          </li>
        ))}
      </ol>

      <div className="page-break" />
      <SheetHead right={`${courseTitle} · answer key`} />
      <h1>Answer key</h1>
      <div className="sheet-sub">Tick-marks for self-evaluation — full explanations live in the NEXUS Practice Arena.</div>
      <div className="key-list">
        {questions.map((q, i) => (
          <div key={q.id} className="key-row page-break-inside">
            <b>
              {i + 1}. {'ABCD'[q.answer]}
            </b>
            <span className="sheet-mute">{q.explanation}</span>
          </div>
        ))}
      </div>
      <SheetFoot text="Question paper generated by MAKAUT NEXUS · question bank tagged by course outcome, Bloom level and paper group." />
    </>
  );
}
